import {
  BUN_TRAILER,
  BUN_VERSION_MATCH,
  BUN_VERSION_MATCH_BANNER,
  BUN_VERSION_MATCH_OLD,
  BUNFS_ROOT,
  BUNFS_ROOT_OLD,
} from "./constants";
import { locateDataSection } from "./formats";
import { findBunSection } from "./macho";
import { parseOffsets } from "./offsets";

export interface BundledFile {
  path: string;
  contents: ArrayBuffer;
  sourcemap?: {
    version: 3;
    file: string;
    debugId?: string;
    mappings: string;
    sources: string[];
  };
}

const corruptionMessage =
  ". Either the binary is corrupted or it's not an executable file generated by `bun build --compile`.";

export class InvalidExecutableError extends Error {
  constructor(msg = "Invalid executable") {
    super(msg + corruptionMessage);
    this.name = "InvalidExecutableError";
  }
}

export class InvalidTrailerError extends InvalidExecutableError {
  constructor() {
    super("Invalid executable trailer");
    this.name = "InvalidTrailerError";
  }
}

export class TotalByteCountMismatchError extends InvalidExecutableError {
  constructor() {
    super("Executable byte count mismatch");
    this.name = "TotalByteCountMismatchError";
  }
}

export class VersionNotFoundError extends InvalidExecutableError {
  constructor() {
    super("Version not found in executable");
    this.name = "VersionNotFoundError";
  }
}

export interface ExtractBundledFilesOptions {
  normaliseEntrypointFileName?: boolean;
}

export function extractBundledFiles(
  compiledBinaryData: DataView | ArrayBuffer,
  options: ExtractBundledFilesOptions = {},
) {
  options = {
    normaliseEntrypointFileName: true,
    ...options,
  };

  if (compiledBinaryData instanceof ArrayBuffer) {
    compiledBinaryData = new DataView(compiledBinaryData);
  }

  const decoder = new TextDecoder();

  // Note: reverse engineering
  // bun/src/StandaloneModuleGraph.zig/StandaloneModuleGraph/toBytes

  // 1. Locate the data section (Mach-O __BUN/__bun or appended to file end)
  const section = locateDataSection(compiledBinaryData);
  if (!section) {
    throw new InvalidTrailerError();
  }

  // 2. Compute trailer offset and validate container-specific invariants
  let dataView: DataView;
  let trailerOffset: number;
  let modulesStart: number;

  if (section.container === "macho") {
    // Mach-O: section.data = [header?][modules][metadata][Offsets][trailer 16B]
    // Different Bun versions have 0, 4, or 8 byte headers; modulesStart is
    // computed after parsing offsets below.
    dataView = section.data;
    trailerOffset = dataView.byteLength - BUN_TRAILER.length;
    modulesStart = 0; // placeholder, computed after parseOffsets
  } else {
    // Appended: full binary = [...native code...][modules][metadata][Offsets 24B][trailer 16B][totalByteCount 8B]
    dataView = section.data;
    trailerOffset = dataView.byteLength - 8 - BUN_TRAILER.length;

    const totalByteCount = dataView.getUint32(dataView.byteLength - 8, true);
    if (dataView.byteLength !== totalByteCount) {
      throw new TotalByteCountMismatchError();
    }

    // modulesStart computed after parsing offsets below
    modulesStart = 0; // placeholder
  }

  // 3. Parse the Offsets struct (variable size: 24 or 32 bytes)
  const offsets = parseOffsets(dataView, trailerOffset);

  // Compute modulesStart from offsetByteCount
  if (section.container === "macho") {
    // [header?][modules+metadata = offsetByteCount][Offsets][trailer 16B]
    modulesStart =
      dataView.byteLength - (offsets.offsetByteCount + offsets.structSize + BUN_TRAILER.length);
  } else {
    // [native code][modules+metadata = offsetByteCount][Offsets][trailer 16B][totalByteCount 8B]
    modulesStart =
      dataView.byteLength - (offsets.offsetByteCount + offsets.structSize + BUN_TRAILER.length + 8);
  }

  // 4. Extract module data
  const modulesEnd = modulesStart + offsets.modulesPtrOffset;
  const modulesData = dataView.buffer.slice(
    dataView.byteOffset + modulesStart,
    dataView.byteOffset + modulesEnd,
  );

  const modulesMetadataStart = modulesEnd;

  // 5. Determine metadata chunk size and format
  // V4 (structSize 32): 52-byte metadata chunks, new format
  // V2/V3 (structSize 24, new format): 28-byte metadata chunks
  // V1 (structSize 24, old format): 32-byte metadata chunks
  let newFormat: boolean;
  let modulesMetadataChunkSize: number;
  if (offsets.structSize === 32) {
    // V4 format: metadata chunks grew to 52 bytes
    newFormat = true;
    modulesMetadataChunkSize = 52;
  } else if (section.container === "macho") {
    // V3: Mach-O with 24-byte offsets, always new format
    newFormat = true;
    modulesMetadataChunkSize = 36;
  } else {
    // V1/V2 appended format: use the existing heuristic
    const structStart = trailerOffset - offsets.structSize;
    const payloadSize =
      dataView.getUint32(structStart - 20, true) + dataView.getUint32(structStart - 16, true);
    newFormat = payloadSize + 1 === offsets.modulesPtrOffset;
    modulesMetadataChunkSize = newFormat ? 28 : 32;
  }

  // 6. Parse each module
  // V3/V4 metadata chunks (>= 36 bytes) have an absolute startOffset at +0
  // that points to where each module's data lives in the modules area.
  // V1/V2 chunks (28/32 bytes) lack this, so we iterate sequentially.
  const hasAbsoluteOffsets = modulesMetadataChunkSize >= 36;

  const bundledFiles: BundledFile[] = [];
  let currentOffset = 0;
  for (let i = 0; i < offsets.modulesPtrLength / modulesMetadataChunkSize; i++) {
    const isEntrypoint = i === offsets.entryPointId;

    const modulesMetadataOffset = modulesMetadataStart + i * modulesMetadataChunkSize;

    if (hasAbsoluteOffsets) {
      currentOffset = dataView.getUint32(modulesMetadataOffset, true);
    }

    const pathLength = dataView.getUint32(modulesMetadataOffset + 4, true);
    const contentsLength = dataView.getUint32(modulesMetadataOffset + 12, true);
    const sourcemapLength = dataView.getUint32(modulesMetadataOffset + 20, true);

    let path = decoder.decode(modulesData.slice(currentOffset, currentOffset + pathLength));
    if (options.normaliseEntrypointFileName && isEntrypoint) {
      path = path.replace(/\/[^\/\\]+$/, "/index.js");
    }
    path = removeBunfsRootFromPath(path);
    if (path[0] !== "/") {
      throw new InvalidExecutableError("Invalid path in bundled file in executable");
    }
    path = removeLeadingSlash(path);

    const contentsStart = currentOffset + pathLength + (newFormat ? 1 : 0);
    const contentsEnd = contentsStart + contentsLength;
    const contents = modulesData.slice(contentsStart, contentsEnd);

    let sourcemap: BundledFile["sourcemap"];
    if (sourcemapLength) {
      const sourcemapMappingsLength = dataView.getUint32(modulesStart + contentsEnd + 5, true);

      if (sourcemapMappingsLength) {
        const sourcemapSourcesCount = dataView.getUint32(modulesStart + contentsEnd + 1, true);

        const mappingsStart = contentsEnd + 9 + sourcemapSourcesCount * 16;
        const mappingsEnd = mappingsStart + sourcemapMappingsLength;

        const contentsEndData = decoder.decode(contents.slice(contents.byteLength - 49));
        const debugId = contentsEndData.match(/^\/\/# debugId=([a-fA-F0-9-]{12,})$/m)?.[1];
        // RegEx copied from the sourcemaps debug-id spec:
        // https://github.com/tc39/source-map/blob/main/proposals/debug-id.md#appendix-a-self-description-of-source-maps-and-javascript-files

        sourcemap = {
          version: 3,
          file: path,
          debugId,
          mappings: decoder.decode(modulesData.slice(mappingsStart, mappingsEnd)),
          sources: [],
        };

        let sourceStart = mappingsEnd;
        for (let j = 0; j < sourcemapSourcesCount; j++) {
          const sourcemapSourceLength = dataView.getUint32(
            modulesStart + contentsEnd + 13 + j * 8,
            true,
          );

          sourcemap.sources.push(
            decoder.decode(modulesData.slice(sourceStart, sourceStart + sourcemapSourceLength)),
          );

          sourceStart += sourcemapSourceLength;
        }
      }
    }

    const bundledFile: BundledFile = { path, contents, sourcemap };
    if (isEntrypoint) {
      bundledFiles.unshift(bundledFile);
    } else {
      bundledFiles.push(bundledFile);
    }

    currentOffset += pathLength + contentsLength + sourcemapLength + (newFormat ? 2 : 0);
  }

  return bundledFiles;
}

function removeBunfsRootFromPath(path: string) {
  if (path.startsWith(BUNFS_ROOT)) {
    return path.slice(BUNFS_ROOT.length);
  }
  if (path.startsWith(BUNFS_ROOT_OLD)) {
    return path.slice(BUNFS_ROOT_OLD.length);
  }
  throw new Error(`Path does not start with Bun-fs root: ${path}`);
}

export function removeLeadingSlash(path: string) {
  return path.replace(/^\/?(?:\.\/)?/, "");
}

export interface BunVersion {
  version: string;
  revision: string;
  newFormat?: boolean;
}

function getExecutableVersionNew(data: Uint8Array, searchLimit: number): BunVersion {
  const versionIndex = data.findIndex((_, index) => {
    if (index >= searchLimit) {
      return false;
    }

    for (let i = 0; i < BUN_VERSION_MATCH.length; i++) {
      if (data[index + i] !== BUN_VERSION_MATCH.charCodeAt(i)) {
        return false;
      }
    }

    return true;
  });

  if (versionIndex === -1) {
    throw new VersionNotFoundError();
  }

  const versionEndIndex = data.indexOf(27, versionIndex + BUN_VERSION_MATCH.length);

  if (versionEndIndex <= 0) {
    throw new VersionNotFoundError();
  }

  const decoder = new TextDecoder();
  const versionString = decoder.decode(
    data.slice(versionIndex + BUN_VERSION_MATCH.length, versionEndIndex),
  );

  const [, version, revision] = versionString.match(/^(.+) \((.+)\)$/) ?? [];

  if (!version) {
    throw new VersionNotFoundError();
  }

  return {
    version,
    revision,
  };
}

function getExecutableVersionOld(data: Uint8Array, searchLimit: number): BunVersion {
  const versionIndex = data.findIndex((_, index) => {
    if (index >= searchLimit) {
      return false;
    }

    for (let i = 0; i < BUN_VERSION_MATCH_OLD.length; i++) {
      if (data[index + i] !== BUN_VERSION_MATCH_OLD.charCodeAt(i)) {
        return false;
      }
    }

    return true;
  });

  if (versionIndex === -1) {
    throw new VersionNotFoundError();
  }

  const versionEndIndex = data.indexOf(58, versionIndex + BUN_VERSION_MATCH_OLD.length);

  if (versionEndIndex <= 0) {
    throw new VersionNotFoundError();
  }

  const decoder = new TextDecoder();
  const versionString = decoder.decode(
    data.slice(versionIndex + BUN_VERSION_MATCH_OLD.length, versionEndIndex),
  );

  const [, version, revision] = versionString.match(/^(.+) \((.+)\)/) ?? [];

  if (!version) {
    throw new VersionNotFoundError();
  }

  return {
    version,
    revision,
  };
}

/**
 * Newest version-string format (Bun 1.4.0+).
 *
 * Bun 1.4.0 stopped embedding a literal version after the ANSI
 * BUN_VERSION_MATCH marker — that became a runtime-substituted placeholder
 * (e.g. `...\x1b[2mv\xc0\x04...`) — but the plain "Bun v<version> (<revision>)"
 * banner is still present in the runtime's read-only data. Scan for it and pull
 * out the semantic version (and revision, if present).
 */
function getExecutableVersionBanner(data: Uint8Array, searchLimit: number): BunVersion {
  const decoder = new TextDecoder();
  const needle = BUN_VERSION_MATCH_BANNER;

  // A "Bun v" occurrence may be help text rather than the version banner, so
  // keep scanning until one actually parses as a version.
  let from = 0;
  for (;;) {
    const index = indexOfBytes(data, needle, from, searchLimit);
    if (index === -1) break;

    const start = index + needle.length;
    const window = decoder.decode(data.subarray(start, Math.min(start + 96, data.length)));

    // Accepts "1.4.0", "1.4.0+63bb0ca0d", "1.1.22-canary.96", each optionally
    // followed by " (revision)". Revision is the "+<sha>" build metadata when
    // present, else the parenthetical (a git sha or a platform string).
    const match = window.match(
      /^(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)(?:\+([0-9A-Za-z]+))?(?:\s*\(([^)]+)\))?/,
    );
    if (match) {
      return { version: match[1], revision: match[2] ?? match[3] ?? "" };
    }

    from = start;
  }

  throw new VersionNotFoundError();
}

/**
 * Find the first occurrence of an ASCII needle in `data` within [from, limit).
 * Returns the byte offset, or -1 if not found.
 */
function indexOfBytes(data: Uint8Array, needle: string, from: number, limit: number): number {
  const max = Math.min(limit, data.length - needle.length + 1);
  for (let i = from; i < max; i++) {
    let matched = true;
    for (let j = 0; j < needle.length; j++) {
      if (data[i + j] !== needle.charCodeAt(j)) {
        matched = false;
        break;
      }
    }
    if (matched) return i;
  }
  return -1;
}

export function getExecutableVersion(data: Uint8Array | ArrayBuffer): BunVersion {
  const bytes = data instanceof ArrayBuffer ? new Uint8Array(data) : data;

  const binary = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  // Determine search limit to exclude embedded module data
  // (prevents matching fake version strings inside bundled files)
  let searchLimit: number;
  const machoSection = findBunSection(binary);
  if (machoSection) {
    // Don't search inside the __BUN section
    searchLimit = machoSection.offset;
  } else {
    // Legacy appended format: don't search past modules start
    searchLimit = getModulesStartLegacy(binary);
  }

  // Try each known version-string format in order, newest binaries last. Bun
  // 1.4.0+ fails the first two matchers (the literal after BUN_VERSION_MATCH is
  // gone) and falls back to the "Bun v" banner.
  const matchers: Array<() => BunVersion> = [
    () => ({ ...getExecutableVersionNew(bytes, searchLimit), newFormat: true }),
    () => ({ ...getExecutableVersionOld(bytes, searchLimit), newFormat: false }),
    () => ({ ...getExecutableVersionBanner(bytes, searchLimit), newFormat: true }),
  ];

  for (const matcher of matchers) {
    try {
      return matcher();
    } catch (e) {
      if (e instanceof VersionNotFoundError) continue;
      throw e;
    }
  }

  throw new VersionNotFoundError();
}

/**
 * Legacy modulesStart calculation for appended format binaries.
 * Used only by getExecutableVersion to determine search bounds.
 */
function getModulesStartLegacy(compiledBinaryData: DataView) {
  if (compiledBinaryData.byteLength <= 48) {
    return compiledBinaryData.byteLength;
  }

  const offsetByteCount = compiledBinaryData.getUint32(compiledBinaryData.byteLength - 48, true);

  return compiledBinaryData.byteLength - (offsetByteCount + 48);
}
